//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UILayer.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BLayerSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Task))]
    public partial class BLayer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback completeProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BLayer() {
            this.Url = global::UILayer.Properties.Settings.Default.UILayer_localhost_BLayer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateLoginCompletedEventHandler ValidateLoginCompleted;
        
        /// <remarks/>
        public event SignUpCompletedEventHandler SignUpCompleted;
        
        /// <remarks/>
        public event completeProfileCompletedEventHandler completeProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskOfBoolean ValidateLogin(string student_id, string password) {
            object[] results = this.Invoke("ValidateLogin", new object[] {
                        student_id,
                        password});
            return ((TaskOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateLoginAsync(string student_id, string password) {
            this.ValidateLoginAsync(student_id, password, null);
        }
        
        /// <remarks/>
        public void ValidateLoginAsync(string student_id, string password, object userState) {
            if ((this.ValidateLoginOperationCompleted == null)) {
                this.ValidateLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateLoginOperationCompleted);
            }
            this.InvokeAsync("ValidateLogin", new object[] {
                        student_id,
                        password}, this.ValidateLoginOperationCompleted, userState);
        }
        
        private void OnValidateLoginOperationCompleted(object arg) {
            if ((this.ValidateLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateLoginCompleted(this, new ValidateLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskOfBoolean SignUp(string first_name, string last_name, string student_id, string password) {
            object[] results = this.Invoke("SignUp", new object[] {
                        first_name,
                        last_name,
                        student_id,
                        password});
            return ((TaskOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void SignUpAsync(string first_name, string last_name, string student_id, string password) {
            this.SignUpAsync(first_name, last_name, student_id, password, null);
        }
        
        /// <remarks/>
        public void SignUpAsync(string first_name, string last_name, string student_id, string password, object userState) {
            if ((this.SignUpOperationCompleted == null)) {
                this.SignUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignUpOperationCompleted);
            }
            this.InvokeAsync("SignUp", new object[] {
                        first_name,
                        last_name,
                        student_id,
                        password}, this.SignUpOperationCompleted, userState);
        }
        
        private void OnSignUpOperationCompleted(object arg) {
            if ((this.SignUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignUpCompleted(this, new SignUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/completeProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaskOfBoolean completeProfile(string phone_no, string address, string city, string country, string state, string emergency_contact, string relationship, string email_id, string student_id) {
            object[] results = this.Invoke("completeProfile", new object[] {
                        phone_no,
                        address,
                        city,
                        country,
                        state,
                        emergency_contact,
                        relationship,
                        email_id,
                        student_id});
            return ((TaskOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void completeProfileAsync(string phone_no, string address, string city, string country, string state, string emergency_contact, string relationship, string email_id, string student_id) {
            this.completeProfileAsync(phone_no, address, city, country, state, emergency_contact, relationship, email_id, student_id, null);
        }
        
        /// <remarks/>
        public void completeProfileAsync(string phone_no, string address, string city, string country, string state, string emergency_contact, string relationship, string email_id, string student_id, object userState) {
            if ((this.completeProfileOperationCompleted == null)) {
                this.completeProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OncompleteProfileOperationCompleted);
            }
            this.InvokeAsync("completeProfile", new object[] {
                        phone_no,
                        address,
                        city,
                        country,
                        state,
                        emergency_contact,
                        relationship,
                        email_id,
                        student_id}, this.completeProfileOperationCompleted, userState);
        }
        
        private void OncompleteProfileOperationCompleted(object arg) {
            if ((this.completeProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.completeProfileCompleted(this, new completeProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TaskOfBoolean : Task {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaskOfBoolean))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Task {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ValidateLoginCompletedEventHandler(object sender, ValidateLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SignUpCompletedEventHandler(object sender, SignUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void completeProfileCompletedEventHandler(object sender, completeProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class completeProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal completeProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskOfBoolean)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591